### ISSUE TITLE
前端升级有好的办法嘛？

### ISSUE THREAD

**Issue by xisuo67** [zhontai/admin.ui.plus#4]
每次升级时会修复部分bug，前端目前升级采用拉分支比对文件，较为麻烦，有没有好的方法？

**Comment by zhontai** [comment]
目前没有好的解决方法。
没有大量修改框架的代码，可以将最新的代码直接覆盖然后对比已修改框架文件。

**Comment by xisuo67** [comment]
目前就是这样处理的，工作量也比较大，一般使用情况都是做了大量改造以适应自己的业务，升级过程比较痛苦

**Comment by zhontai** [comment]
前端是全框架定制化，所以升级可以选择性升级
