### ISSUE TITLE
随着关注逐渐增多，建议文档加强

### ISSUE THREAD

**Issue by xisuo67** [zhontai/admin.ui.plus#6]
文档部分不太健全，建议在高速迭代的同时，逐步完善文档的建立，不然随着用户增多，越来越多人会在群里反馈同样的问题，耗时耗力

**Comment by zhontai** [comment]
感谢建议，目前在推进5.0微服务项目，后续会发力完善文档

**Comment by xisuo67** [comment]
期待您的项目
